name: TestFlight Deployment

on:
  push:
    branches:
      - main  # Replace 'main' with your branch name if different

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
      # Step to set up Flutter with the same version you are using locally
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter_version: '3.22.2'  # Set the version of Flutter to match your local version
      # Debugging: List the directory structure
      - name: List current directory structure
        run: pwd  # Print the current working directory

      # - name: List the contents of the ios_deployment_demo directory
      #   run: ls -R ios_deployment_demo  # List the directory structure inside ios_deployment_demo

      - name: List the contents of the ios directory
        run: ls -R ./ios  # List the directory structure of the ios folder

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
           ruby-version: '3.0'  # Specify the Ruby version compatible with Fastlane

      - name: Install dependencies
        working-directory: ./ios

        run: |
          gem install bundler
          bundle install
      # Set up Fastlane Match to sync profiles
      - name: Set up Fastlane Match
        working-directory: ./ios
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}  # Pass MATCH_PASSWORD to environment variables
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}  # Pass FASTLANE_PASSWORD to environment variables
          FASTLANE_APPLE_ID_PASSWORD: ${{ secrets.FASTLANE_APPLE_ID_PASSWORD }}  # Apple ID password
        run: |
          gem install fastlane
          fastlane init
          
       # Step to generate the missing xcconfig file
      - name: Generate Generated.xcconfig file
        working-directory: ./ios  # Adjust this if the file needs to be generated elsewhere
        run: |
          flutter build ios  # or the command that generates the file
      - name: Set up fastlane environment
        working-directory: ./ios
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          APP_STORE_CONNECT_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}  
          FASTLANE_APPLE_ID_PASSWORD: ${{ secrets.FASTLANE_APPLE_ID_PASSWORD }}  # Apple ID password
        run: |
          bundle exec fastlane beta  # Run the Fastlane lane to upload to TestFlight
